name: deploy_code 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: fetch latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            cd /usr/share/nginx/html && git pull
            cp /usr/share/nginx/html/nginx.conf /etc/nginx/nginx.conf
